- hosts: client1
  tasks:
  - name: "sync website"
    synchronize:
      src: /home/ubuntu/site/
      dest: /var/www/{{ domain }}
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no
